import { Transaction } from "@/types/types";

export const mockTransactions: Transaction[] = [
  {
    id: "37424-242356-99100",
    bill_address1: "123 Elm St",
    bill_address2: "Apt 4B",
    bill_address_id: 101,
    bill_city: "Springfield",
    bill_contact_email: "john.doe@example.com",
    bill_contact_first_name: "John",
    bill_contact_id: 201,
    bill_contact_last_name: "Doe",
    bill_contact_phone: "555-1234",
    bill_country: "USA",
    bill_customer_account: "AC12345",
    bill_customer_id: 301,
    bill_customer_name: "Acme Corp",
    bill_postal_code: "62701",
    bill_state: "IL",
    created_by: "1",
    created_at: "2024-07-01",
    end_date: "2025-07-01",
    error_message: "",
    updated_at: "2024-07-05",
    updated_by: "2",
    notification_date: "2024-07-02",
    organization: "PAI",
    quantity: 1,
    reference_code: "REF001",
    ship_address1: "456 Oak St",
    ship_address2: "",
    ship_address_id: 102,
    ship_city: "Springfield",
    ship_contact_email: "jane.doe@example.com",
    ship_contact_first_name: "Jane",
    ship_contact_id: 202,
    ship_contact_last_name: "Doe",
    ship_contact_phone: "555-5678",
    ship_country: "USA",
    ship_customer_account: "AC67890",
    ship_customer_id: 302,
    ship_customer_name: "Beta LLC",
    ship_postal_code: "62702",
    ship_state: "IL",
    source_reference_date: "2024-06-30",
    source_reference_id: "501",
    source_reference_number: "SRC001",
    start_date: "2024-07-01",
    transaction_action: "New",
    transaction_date: "2024-07-01",
    transaction_number: 1001,
    transaction_source: "Manual",
    transaction_status: "Waiting for validation",
    transaction_type: "Sales",
    asset: {
      id: "660e8400-e29b-41d4-a716-100000",
      active_seats: 0,
      created_by: 1,
      creation_date: "2024-01-15",
      active: false,
      end_date: "2025-01-15",
      expired_seats: 0,
      license_key: "",
      license_server_seat_count: 0,
      organization: "PAI",
      osc_seat_count: 1,
      renewal_seats: 0,
      revoked_seats: 0,
      start_date: "2024-01-15",
      suspended_seats: 0,
      terminated_seats: 0,
    },
    osc_product: {
      organization: "PAI",
      osc_product_id: 1,
      osc_part_number: "PSCP-WG-MAIN-2",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
      product_description: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
      duration: "2YR",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-MAIN-2",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "MAINTENANCE AND SUPPORT",
      attribute2: "2YR",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    }
  },
  {
    id: "37424-242356-99101",
    bill_address1: "789 Pine St",
    bill_address2: "Suite 12",
    bill_address_id: 103,
    bill_city: "Shelbyville",
    bill_contact_email: "alice.smith@example.com",
    bill_contact_first_name: "Alice",
    bill_contact_id: 203,
    bill_contact_last_name: "Smith",
    bill_contact_phone: "555-8765",
    bill_country: "USA",
    bill_customer_account: "AC54321",
    bill_customer_id: 303,
    bill_customer_name: "Gamma Inc",
    bill_postal_code: "62565",
    bill_state: "IL",
    created_by: "3",
    created_at: "2024-07-10",
    end_date: "2025-01-10",
    error_message: "Invalid data",
    updated_at: "2024-07-12",
    updated_by: "4",
    notification_date: "2024-07-11",
    organization: "PAI",
    quantity: 1,
    reference_code: "REF002",
    ship_address1: "321 Maple St",
    ship_address2: "Floor 3",
    ship_address_id: 104,
    ship_city: "Shelbyville",
    ship_contact_email: "bob.jones@example.com",
    ship_contact_first_name: "Bob",
    ship_contact_id: 204,
    ship_contact_last_name: "Jones",
    ship_contact_phone: "555-4321",
    ship_country: "USA",
    ship_customer_account: "AC98765",
    ship_customer_id: 304,
    ship_customer_name: "Delta Ltd",
    ship_postal_code: "62566",
    ship_state: "IL",
    source_reference_date: "2024-07-09",
    source_reference_id: "502",
    source_reference_number: "SRC002",
    start_date: "2024-07-10",
    transaction_action: "New",
    transaction_date: "2024-07-10",
    transaction_number: 1002,
    transaction_source: "Oracle ERP",
    transaction_status: "Waiting for validation",
    transaction_type: "Sales",
    asset: {
      id: "660e8400-e29b-41d4-a716-111111",
      active_seats: 1,
      created_by: 3,
      creation_date: "2024-02-20",
      active: false,
      end_date: "2024-08-20",
      expired_seats: 0,
      license_key: "ABC-5678-1234-EFGH",
      license_server_seat_count: 1,
      organization: "PAI",
      osc_seat_count: 1,
      renewal_seats: 0,
      revoked_seats: 0,
      start_date: "2024-02-20",
      suspended_seats: 0,
      terminated_seats: 0,
      osc_product: {
        organization: "PAI",
        osc_product_id: 2,
        osc_part_number: "PSCP-WG-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-WG-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
      },
    },
    osc_product: {
      organization: "PAI",
      osc_product_id: 2,
      osc_part_number: "PSCP-WG-MAIN-1",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
      product_description: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
      duration: "YR",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-MAIN-1",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "MAINTENANCE AND SUPPORT",
      attribute2: "YR",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    }
  },
  {
    id: "37424-242356-99102",
    bill_address1: "654 Birch St",
    bill_address2: "Building A",
    bill_address_id: 105,
    bill_city: "Capital City",
    bill_contact_email: "charlie.brown@example.com",
    bill_contact_first_name: "Charlie",
    bill_contact_id: 205,
    bill_contact_last_name: "Brown",
    bill_contact_phone: "555-6789",
    bill_country: "USA",
    bill_customer_account: "AC67890",
    bill_customer_id: 305,
    bill_customer_name: "Epsilon Co",
    bill_postal_code: "62703",
    bill_state: "IL",
    created_by: "5",
    created_at: "2024-07-15",
    end_date: "2024-10-15",
    error_message: "",
    updated_at: "2024-07-16",
    updated_by: "6",
    notification_date: "2024-07-16",
    organization: "PAI",
    quantity: 1,
    reference_code: "REF003",
    ship_address1: "987 Cedar St",
    ship_address2: "Unit 5",
    ship_address_id: 106,
    ship_city: "Capital City",
    ship_contact_email: "david.wilson@example.com",
    ship_contact_first_name: "David",
    ship_contact_id: 206,
    ship_contact_last_name: "Wilson",
    ship_contact_phone: "555-7890",
    ship_country: "USA",
    ship_customer_account: "AC11223",
    ship_customer_id: 306,
    ship_customer_name: "Zeta Enterprises",
    ship_postal_code: "62704",
    ship_state: "IL",
    source_reference_date: "2024-07-14",
    source_reference_id: "503",
    source_reference_number: "SRC003",
    start_date: "2024-07-15",
    transaction_action: "Update",
    transaction_date: "2024-07-15",
    transaction_number: 1003,
    transaction_source: "Oracle ERP",
    transaction_status: "Completed",
    transaction_type: "Sales",
    asset: {
      id: "660e8400-e29b-41d4-a716-199999",
      active_seats: 1,
      created_by: 5,
      creation_date: "2024-03-10",
      active: true,
      end_date: "2026-03-10",
      expired_seats: 0,
      license_key: "LMN-9012-3456-IJKL",
      license_server_seat_count: 1,
      organization: "PAI",
      osc_seat_count: 1,
      renewal_seats: 0,
      revoked_seats: 0,
      start_date: "2024-03-10",
      suspended_seats: 0,
      terminated_seats: 0,
      osc_product: {
        organization: "PAI",
        osc_product_id: 3,
        osc_part_number: "PSCP-WG-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
        product_description: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-WG-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
      },
    },
    osc_product: {
      organization: "PAI",
      osc_product_id: 3,
      osc_part_number: "PSCP-WG-0001",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
      product_description: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
      duration: "EA",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-0001",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "LICENSE",
      attribute2: "EA",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    }
  },
  {
    id: "37424-242356-99103",
    bill_address1: "234 Walnut St",
    bill_address2: "Suite 3A",
    bill_address_id: 108,
    bill_city: "Gotham",
    bill_contact_email: "frank.miller@example.com",
    bill_contact_first_name: "Frank",
    bill_contact_id: 208,
    bill_contact_last_name: "Miller",
    bill_contact_phone: "555-2345",
    bill_country: "USA",
    bill_customer_account: "AC34567",
    bill_customer_id: 308,
    bill_customer_name: "Iota Systems",
    bill_postal_code: "62901",
    bill_state: "IL",
    created_by: "9",
    created_at: "2024-07-25",
    end_date: "2026-01-25",
    error_message: "",
    updated_at: "2024-07-26",
    updated_by: "10",
    notification_date: "2024-07-26",
    organization: "PAI",
    quantity: 1,
    reference_code: "REF005",
    ship_address1: "654 Birch St",
    ship_address2: "",
    ship_address_id: 109,
    ship_city: "Gotham",
    ship_contact_email: "lucas.green@example.com",
    ship_contact_first_name: "Lucas",
    ship_contact_id: 209,
    ship_contact_last_name: "Green",
    ship_contact_phone: "555-4567",
    ship_country: "USA",
    ship_customer_account: "AC78901",
    ship_customer_id: 309,
    ship_customer_name: "Kappa Ltd",
    ship_postal_code: "62902",
    ship_state: "IL",
    source_reference_date: "2024-07-24",
    source_reference_id: "504",
    source_reference_number: "SRC004",
    start_date: "2024-07-25",
    transaction_action: "Update",
    transaction_date: "2024-07-25",
    transaction_number: 1004,
    transaction_source: "Oracle ERP",
    transaction_status: "Waiting for source update",
    transaction_type: "Eval",
    asset: {
      id: "660e8400-e29b-41d4-a716-122222",
      active_seats: 1,
      created_by: 7,
      creation_date: "2024-04-01",
      active: true,
      end_date: "2025-10-01",
      expired_seats: 0,
      license_key: "OPQ-3456-7890-MNOP",
      license_server_seat_count: 1,
      organization: "PAI",
      osc_seat_count: 1,
      renewal_seats: 0,
      revoked_seats: 0,
      start_date: "2024-04-01",
      suspended_seats: 0,
      terminated_seats: 0,
      osc_product: {
        organization: "PAI",
        osc_product_id: 4,
        osc_part_number: "PSCP-ST-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro QC/Index Station Software License",
        product_description: "PaperStream Capture Pro QC/Index Station Software License",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-ST-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
      }
    },
    osc_product: {
      organization: "PAI",
      osc_product_id: 4,
      osc_part_number: "PSCP-ST-0001",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro QC/Index Station Software License",
      product_description: "PaperStream Capture Pro QC/Index Station Software License",
      duration: "EA",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-ST-0001",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "LICENSE",
      attribute2: "EA",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    }
  }
];
