export const mockProducts = [
    {
        id: "1",
        organization: 1,
        osc_product_id: 1,
        osc_part_number: "PSCP-WG-MAIN-2",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
        product_description: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
        duration: "2YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-WG-MAIN-2",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "2YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "2",
        organization: 1,
        osc_product_id: 2,
        osc_part_number: "PSCP-WG-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-WG-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "3",
        organization: 1,
        osc_product_id: 3,
        osc_part_number: "PSCP-WG-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
        product_description: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-WG-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "4",
        organization: 1,
        osc_product_id: 4,
        osc_part_number: "PSCP-ST-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro QC/Index Station Software License",
        product_description: "PaperStream Capture Pro QC/Index Station Software License",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-ST-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "5",
        organization: 1,
        osc_product_id: 5,
        osc_part_number: "PSCP-MV-MAIN-3",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Mid-Volume 3 Year Maintenance",
        product_description: "PaperStream Capture Pro Mid-Volume 3 Year Maintenance",
        duration: "3YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-MV-MAIN-3",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "3YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "6",
        organization: 1,
        osc_product_id: 6,
        osc_part_number: "PSCP-MV-MAIN-2",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Mid-Volume 2 Year Maintenance",
        product_description: "PaperStream Capture Pro Mid-Volume 2 Year Maintenance",
        duration: "2YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-MV-MAIN-2",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "2YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "7",
        organization: 1,
        osc_product_id: 7,
        osc_part_number: "PSCP-MV-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Mid-Volume 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Mid-Volume 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-MV-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "8",
        organization: 1,
        osc_product_id: 8,
        osc_part_number: "PSCP-MV-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Mid-Volume Software License with 1yr maintenance contract",
        product_description: "PaperStream Capture Pro Mid-Volume Software License with 1yr maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-MV-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "9",
        organization: 1,
        osc_product_id: 9,
        osc_part_number: "PSCP-LV-MAIN-3",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Low-Volume 3 Year Maintenance",
        product_description: "PaperStream Capture Pro Low-Volume 3 Year Maintenance",
        duration: "3YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-LV-MAIN-3",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "3YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "10",
        organization: 1,
        osc_product_id: 10,
        osc_part_number: "PSCP-LV-MAIN-2",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Low-Volume 2 Year Maintenance",
        product_description: "PaperStream Capture Pro Low-Volume 2 Year Maintenance",
        duration: "2YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-LV-MAIN-2",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "2YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "11",
        organization: 1,
        osc_product_id: 11,
        osc_part_number: "PSCP-LV-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Low-Volume 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Low-Volume 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-LV-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "12",
        organization: 1,
        osc_product_id: 12,
        osc_part_number: "PSCP-LV-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Low-Volume Software License with 1yr maintenance contract",
        product_description: "PaperStream Capture Pro Low-Volume Software License with 1yr maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-LV-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "13",
        organization: 1,
        osc_product_id: 13,
        osc_part_number: "PSCP-IM-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Import 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Import 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-IM-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "14",
        organization: 1,
        osc_product_id: 14,
        osc_part_number: "PSCP-IM-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Import Software License with 1 yr maintenance contract",
        product_description: "PaperStream Capture Pro Import Software License with 1 yr maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-IM-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "15",
        organization: 1,
        osc_product_id: 15,
        osc_part_number: "PSCP-DP-MAIN-3",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Departmental 3 Year Maintenance",
        product_description: "PaperStream Capture Pro Departmental 3 Year Maintenance",
        duration: "3YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-DP-MAIN-3",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "3YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "16",
        organization: 1,
        osc_product_id: 16,
        osc_part_number: "PSCP-DP-MAIN-2",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Departmental 2 Year Maintenance",
        product_description: "PaperStream Capture Pro Departmental 2 Year Maintenance",
        duration: "2YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-DP-MAIN-2",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "2YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "17",
        organization: 1,
        osc_product_id: 17,
        osc_part_number: "PSCP-DP-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Departmental 1 Year Maintenance",
        product_description: "PaperStream Capture Pro Departmental 1 Year Maintenance",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-DP-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "18",
        organization: 1,
        osc_product_id: 18,
        osc_part_number: "PSCP-DP-0001",
        product_type: "SOFTWARE",
        product_name: "PaperStream Capture Pro Departmental Software License with 1yr maintenance",
        product_description: "PaperStream Capture Pro Departmental Software License with 1yr maintenance",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "PSCP-DP-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "PAPERSTREAM",
        attribute5: "PSCPRO",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "19",
        organization: 1,
        osc_product_id: 19,
        osc_part_number: "ENXC-LOW-0001",
        product_type: "SOFTWARE",
        product_name: "Easy NX Connect Perpetual Software License for fi-7300NX for less than 1M scans and 1 year maintenance contract",
        product_description: "Easy NX Connect Perpetual Software License for fi-7300NX for less than 1M scans and 1 year maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "ENXC-LOW-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "WRKGRP",
        attribute5: "FI-7300NX",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "20",
        organization: 1,
        osc_product_id: 20,
        osc_part_number: "ENXC-HIGH-MAIN-1",
        product_type: "SOFTWARE",
        product_name: "1 year maintenance option for high end perpetual",
        product_description: "1 year maintenance option for high end perpetual",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "ENXC-HIGH-MAIN-1",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "MAINTENANCE AND SUPPORT",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "WRKGRP",
        attribute5: "FI-7300NX",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "21",
        organization: 1,
        osc_product_id: 21,
        osc_part_number: "ENXC-HIGH-0001",
        product_type: "SOFTWARE",
        product_name: "Easy NX Connect Perpetual Software License for fi-7300NX with unlimited scans and 1 year maintenance contract",
        product_description: "Easy NX Connect Perpetual Software License for fi-7300NX with unlimited scans and 1 year maintenance contract",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "ENXC-HIGH-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "LICENSE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "WRKGRP",
        attribute5: "FI-7300NX",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "22",
        organization: 1,
        osc_product_id: 22,
        osc_part_number: "EDGEX-SUBS-0001",
        product_type: "SOFTWARE",
        product_name: "EdgeXperience Capture Service Software, 1-Year Subscription",
        product_description: "EdgeXperience Capture Service Software, 1-Year Subscription",
        duration: "YR",
        vendor_name: "PFUJ",
        vendor_part_number: "EDGEX-SUBS-0001",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "SOFTWARE",
        attribute2: "YR",
        attribute3: "SOFTWARE",
        attribute4: "WRKGRP",
        attribute5: "FI-7300NX",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    },
    {
        id: "23",
        organization: 1,
        osc_product_id: 23,
        osc_part_number: "00-220-101-9001-R",
        product_type: "SOFTWARE",
        product_name: "00-220-101-9001-R WINFAX SOFTWARE (TAC LAB)",
        product_description: "00-220-101-9001-R WINFAX SOFTWARE (TAC LAB)",
        duration: "EA",
        vendor_name: "PFUJ",
        vendor_part_number: "00-220-101-9001-R",
        license_source_set: "SourceSet1",
        source_name: "VendorSource1",
        attribute1: "SOFTWARE",
        attribute2: "EA",
        attribute3: "SOFTWARE",
        attribute4: "COMMON-SEG",
        attribute5: "COMMON-MODEL",
        eval_set_name: "EvalSet1",
        renewal_set_name: "RenewalSet1",
        new_set_name: "NewSet1",
        active: true,
    }
];
