export const mockAssets = [
  {
    id: "660e8400-e29b-41d4-a716-100000",
    active_seats: 0,
    created_by: 1,
    creation_date: "2024-01-15",
    active: true,
    end_date: "2026-01-14",
    expired_seats: 0,
    license_key: "",
    license_server_seat_count: 0,
    organization: "PAI",
    osc_seat_count: 1,
    renewal_seats: 0,
    revoked_seats: 0,
    start_date: "2024-01-15",
    suspended_seats: 0,
    terminated_seats: 0,
    transactions: [
      {
        id: "37424-242356-99100",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
      {
        id: "37424-242356-99101",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
    ],
    osc_product: {
      organization: "PAI",
      osc_product_id: 1,
      osc_part_number: "PSCP-WG-MAIN-2",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
      product_description: "PaperStream Capture Pro Workgroup 2 Year Maintenance",
      duration: "2YR",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-MAIN-2",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "MAINTENANCE AND SUPPORT",
      attribute2: "2YR",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    },
    seats: [
      {
        seat_number: "1",
        osc_license_status: "Active",
        osc_start_date: "2024-07-01",
        osc_end_date: "2026-06-30",
        license_server_status: "Active",
        license_server_start_date: "2024-07-01",
        license_server_end_date: "2026-06-30",
      }
    ],
    license_owner: {
      address1: "321 Maple St",
      address2: "Floor 3",
      address_id: 104,
      ship_city: "Shelbyville",
      ship_contact_email: "bob.jones@example.com",
      contact_first_name: "Bob",
      contact_id: 204,
      contact_last_name: "Jones",
      contact_phone: "555-4321",
      country: "USA",
      customer_account: "AC98765",
      customer_id: 304,
      customer_name: "Delta Ltd",
      postal_code: "62566",
      state: "IL",
    }
  },
  {
    id: "660e8400-e29b-41d4-a716-111111",
    active_seats: 1,
    created_by: 3,
    creation_date: "2024-02-20",
    active: false,
    end_date: "2025-02-19",
    expired_seats: 0,
    license_key: "ABC-5678-1234-EFGH",
    license_server_seat_count: 1,
    organization: "PAI",
    osc_seat_count: 1,
    renewal_seats: 0,
    revoked_seats: 0,
    start_date: "2024-02-20",
    suspended_seats: 0,
    terminated_seats: 0,
    transactions: [
      {
        id: "37424-242356-99100",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
      {
        id: "37424-242356-99101",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
    ],
    osc_product: {
      organization: "PAI",
      osc_product_id: 2,
      osc_part_number: "PSCP-WG-MAIN-1",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
      product_description: "PaperStream Capture Pro Workgroup 1 Year Maintenance",
      duration: "YR",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-MAIN-1",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "MAINTENANCE AND SUPPORT",
      attribute2: "YR",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    },
    seats: [
      {
        seat_number: "1",
        osc_license_status: "Active",
        osc_start_date: "2024-07-10",
        osc_end_date: "2025-07-09",
        license_server_status: "Active",
        license_server_start_date: "2024-07-10",
        license_server_end_date: "2025-07-09",
      }
    ],
    license_owner: {
      address1: "321 Maple St",
      address2: "Floor 3",
      address_id: 104,
      ship_city: "Shelbyville",
      ship_contact_email: "bob.jones@example.com",
      contact_first_name: "Bob",
      contact_id: 204,
      contact_last_name: "Jones",
      contact_phone: "555-4321",
      country: "USA",
      customer_account: "AC98765",
      customer_id: 304,
      customer_name: "Delta Ltd",
      postal_code: "62566",
      state: "IL",
    }
  },
  {
    id: "660e8400-e29b-41d4-a716-199999",
    active_seats: 1,
    created_by: 5,
    creation_date: "2024-03-10",
    active: true,
    end_date: null,
    expired_seats: 0,
    license_key: "LMN-9012-3456-IJKL",
    license_server_seat_count: 1,
    organization: "PAI",
    osc_seat_count: 1,
    renewal_seats: 0,
    revoked_seats: 0,
    start_date: "2024-03-10",
    suspended_seats: 0,
    terminated_seats: 0,
    transactions: [
      {
        id: "37424-242356-99100",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
      {
        id: "37424-242356-99101",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
    ],
    osc_product: {
      organization: "PAI",
      osc_product_id: 3,
      osc_part_number: "PSCP-WG-0001",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
      product_description: "PaperStream Capture Pro Workgroup Software License with 1yr maintenance contract",
      duration: "EA",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-WG-0001",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "LICENSE",
      attribute2: "EA",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    },
    seats: [
      {
        seat_number: "1",
        osc_license_status: "Active",
        osc_start_date: "2024-07-15",
        osc_end_date: null,
        license_server_status: "Active",
        license_server_start_date: "2024-07-15",
        license_server_end_date: null,
      }
    ],
    license_owner: {
      address1: "321 Maple St",
      address2: "Floor 3",
      address_id: 104,
      ship_city: "Shelbyville",
      ship_contact_email: "bob.jones@example.com",
      contact_first_name: "Bob",
      contact_id: 204,
      contact_last_name: "Jones",
      contact_phone: "555-4321",
      country: "USA",
      customer_account: "AC98765",
      customer_id: 304,
      customer_name: "Delta Ltd",
      postal_code: "62566",
      state: "IL",
    }
  },
  {
    id: "660e8400-e29b-41d4-a716-122222",
    active_seats: 1,
    created_by: 7,
    creation_date: "2024-04-01",
    active: true,
    end_date: "2025-10-01",
    expired_seats: 0,
    license_key: "OPQ-3456-7890-MNOP",
    license_server_seat_count: 1,
    organization: "PAI",
    osc_seat_count: 1,
    renewal_seats: 0,
    revoked_seats: 0,
    start_date: "2024-04-01",
    suspended_seats: 0,
    terminated_seats: 0,
    transactions: [
      {
        id: "37424-242356-99100",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
      {
        id: "37424-242356-99101",
        transaction_date: "2024-07-01",
        transaction_number: 1001,
        transaction_source: "Manual",
        transaction_status: "Waiting for validation",
        transaction_type: "Sales"
      },
    ],
    osc_product: {
      organization: "PAI",
      osc_product_id: 4,
      osc_part_number: "PSCP-ST-0001",
      product_type: "SOFTWARE",
      product_name: "PaperStream Capture Pro QC/Index Station Software License",
      product_description: "PaperStream Capture Pro QC/Index Station Software License",
      duration: "EA",
      vendor_name: "PFUJ",
      vendor_part_number: "PSCP-ST-0001",
      license_source_set: "SourceSet1",
      source_name: "VendorSource1",
      attribute1: "LICENSE",
      attribute2: "EA",
      attribute3: "SOFTWARE",
      attribute4: "PAPERSTREAM",
      attribute5: "PSCPRO",
      eval_set_name: "EvalSet1",
      renewal_set_name: "RenewalSet1",
      new_set_name: "NewSet1",
      active: true,
    },
    seats: [
      {
        seat_number: "1",
        osc_license_status: "Active",
        osc_start_date: "2024-07-25",
        osc_end_date: null,
        license_server_status: "Active",
        license_server_start_date: "2024-07-25",
        license_server_end_date: null,
      }
    ],
    license_owner: {
      address1: "321 Maple St",
      address2: "Floor 3",
      address_id: 104,
      ship_city: "Shelbyville",
      ship_contact_email: "bob.jones@example.com",
      contact_first_name: "Bob",
      contact_id: 204,
      contact_last_name: "Jones",
      contact_phone: "555-4321",
      country: "USA",
      customer_account: "AC98765",
      customer_id: 304,
      customer_name: "Delta Ltd",
      postal_code: "62566",
      state: "IL",
    }
  }
];
